export const passeios = [
    {
        nome: "Cristo Redentor",
        id: "cristoRedentor",
        coords: [-22.951916, -43.210487],
        imagem01: "images/passeios/cristoRedentor/CristoRedentor01.webp",
        imagem02: "images/passeios/cristoRedentor/CristoRedentor02.webp",
        imagem03: "images/passeios/cristoRedentor/CristoRedentor03.webp",
        imagem04: "images/passeios/cristoRedentor/CristoRedentor04.webp",
        imagem05: "images/passeios/cristoRedentor/CristoRedentor05.webp",
        imagem06: "images/passeios/cristoRedentor/CristoRedentor06.webp",
        descricao: "Conheça uma das 7 maravilhas do mundo moderno com uma vista panorâmica incrível do Rio de Janeiro.",
        alt: "Foto do Cristo Redentor",
        preco: "R$180"
    },
    {
        nome: "Pão de Açúcar",
        id: "paoDeAcucar",
        coords: [-22.948531, -43.156381],
        imagem01: "images/passeios/paoDeAcucar/paoDeAcucar01.webp",
        imagem02: "images/passeios/paoDeAcucar/paoDeAcucar02.webp",
        imagem03: "images/passeios/paoDeAcucar/paoDeAcucar03.webp",
        imagem04: "images/passeios/paoDeAcucar/paoDeAcucar04.webp",
        imagem05: "images/passeios/paoDeAcucar/paoDeAcucar05.webp",
        imagem06: "images/passeios/paoDeAcucar/paoDeAcucar06.webp",
        descricao: "Suba de bondinho e aproveite uma das vistas mais icônicas do Rio, perfeita para fotos ao pôr do sol.",
        alt: "Foto do Pão de Açúcar",
        preco: "R$220"
    },
    {
        nome: "Praia de Copacabana",
        id: "copacabana",
        coords: [-22.971964, -43.182543],
        imagem01: "images/passeios/copacabana/Copa01.webp",
        imagem02: "images/passeios/copacabana/Copa02.webp",
        imagem03: "images/passeios/copacabana/Copa03.webp",
        imagem04: "images/passeios/copacabana/Copa04.webp",
        imagem05: "images/passeios/copacabana/Copa05.webp",
        imagem06: "images/passeios/copacabana/Copa06.webp",
        descricao: "A praia mais famosa do Brasil, com seu calçadão icônico e uma energia única.",
        alt: "Foto da Praia de Copacabana",
        preco: "R$120"
    },
    {
        nome: "Praia de Ipanema",
        id: "ipanema",
        coords: [-22.983956, -43.209587],
        imagem01: "images/passeios/ipanema/Ipanema01.webp",
        imagem02: "images/passeios/ipanema/Ipanema02.webp",
        imagem03: "images/passeios/ipanema/Ipanema03.webp",
        imagem04: "images/passeios/ipanema/Ipanema04.webp",
        imagem05: "images/passeios/ipanema/Ipanema05.webp",
        imagem06: "images/passeios/ipanema/Ipanema06.webp",
        descricao: "Relaxe em uma das praias mais charmosas do mundo e aproveite o famoso pôr do sol.",
        alt: "Foto da Praia de Ipanema",
        preco: "R$130"
    },
    {
        nome: "Escadaria Selarón",
        id: "selaron",
        coords: [-22.915235, -43.179221],
        imagem01: "images/passeios/selaron/Selaron01.webp",
        imagem02: "images/passeios/selaron/Selaron02.webp",
        imagem03: "images/passeios/selaron/Selaron03.webp",
        imagem04: "images/passeios/selaron/Selaron04.webp",
        imagem05: "images/passeios/selaron/Selaron05.webp",
        imagem06: "images/passeios/selaron/Selaron06.webp",
        descricao: "Um dos pontos mais coloridos do Rio, perfeito para fotos e para conhecer arte urbana.",
        alt: "Foto da Escadaria Selarón",
        preco: "R$100"
    },
    {
        nome: "Arcos da Lapa",
        id: "lapa",
        coords: [-22.913708, -43.180409],
        imagem01: "images/passeios/lapa/Lapa01.webp",
        imagem02: "images/passeios/lapa/Lapa02.webp",
        imagem03: "images/passeios/lapa/Lapa03.webp",
        imagem04: "images/passeios/lapa/Lapa04.webp",
        imagem05: "images/passeios/lapa/Lapa05.webp",
        imagem06: "images/passeios/lapa/Lapa06.webp",
        descricao: "Conheça a vida noturna carioca e os famosos Arcos da Lapa, símbolo histórico da cidade.",
        alt: "Foto dos Arcos da Lapa",
        preco: "R$140"
    },
    {
        nome: "Parque Lage",
        id: "parqueLage",
        coords: [-22.960762, -43.215937],
        imagem01: "images/passeios/parquelage/Lage01.webp",
        imagem02: "images/passeios/parquelage/Lage02.webp",
        imagem03: "images/passeios/parquelage/Lage03.webp",
        imagem04: "images/passeios/parquelage/Lage04.webp",
        imagem05: "images/passeios/parquelage/Lage05.webp",
        imagem06: "images/passeios/parquelage/Lage06.webp",
        descricao: "Um refúgio verde com vista para o Cristo, perfeito para passeios tranquilos e fotos incríveis.",
        alt: "Foto do Parque Lage",
        preco: "R$110"
    },
    {
        nome: "Mirante Dona Marta",
        id: "donaMarta",
        coords: [-22.945814, -43.197566],
        imagem01: "images/passeios/mirante/Mirante01.webp",
        imagem02: "images/passeios/mirante/Mirante02.webp",
        imagem03: "images/passeios/mirante/Mirante03.webp",
        imagem04: "images/passeios/mirante/Mirante04.webp",
        imagem05: "images/passeios/mirante/Mirante05.webp",
        imagem06: "images/passeios/mirante/Mirante06.webp",
        descricao: "Uma das melhores vistas panorâmicas do Rio, ideal para ver o nascer ou pôr do sol.",
        alt: "Foto do Mirante Dona Marta",
        preco: "R$150"
    }
];

