export const passeios = [
    {
        nome: "Cristo Redentor",
        coords: [-22.951916, -43.210487],
        imagem01: "images/passeios/cristoRedentor/CristoRedentor01.jpg",
        imagem02: "images/passeios/cristoRedentor/CristoRedentor02.jpg",
        imagem03: "images/passeios/cristoRedentor/CristoRedentor03.jpg",
        imagem04: "images/passeios/cristoRedentor/CristoRedentor04.jpg",
        imagem05: "images/passeios/cristoRedentor/CristoRedentor05.jpg",
        imagem06: "images/passeios/cristoRedentor/CristoRedentor06.jpg",
        descricao: "Conheça uma das 7 maravilhas do mundo moderno com uma vista panorâmica incrível do Rio de Janeiro.",
        preco: "R$180"
    },
    {
        nome: "Pão de Açúcar",
        coords: [-22.948531, -43.156381],
        imagem01: "images/passeios/paoDeAcucar/paoDeAcucar01.jpg",
        imagem02: "images/passeios/paoDeAcucar/paoDeAcucar02.jpg",
        imagem03: "images/passeios/paoDeAcucar/paoDeAcucar03.jpg",
        imagem04: "images/passeios/paoDeAcucar/paoDeAcucar04.jpg",
        imagem05: "images/passeios/paoDeAcucar/paoDeAcucar05.jpg",
        imagem06: "images/passeios/paoDeAcucar/paoDeAcucar06.jpg",
        descricao: "Suba de bondinho e aproveite uma das vistas mais icônicas do Rio, perfeita para fotos ao pôr do sol.",
        preco: "R$220"
    },
    {
        nome: "Praia de Copacabana",
        coords: [-22.971964, -43.182543],
        imagem01: "images/passeios/cristoRedentor/CristoRedentor01.jpg",
        imagem02: "images/passeios/copacabana/Copa02.jpg",
        imagem03: "images/passeios/copacabana/Copa03.jpg",
        imagem04: "images/passeios/copacabana/Copa04.jpg",
        imagem05: "images/passeios/copacabana/Copa05.jpg",
        imagem06: "images/passeios/copacabana/Copa06.jpg",
        descricao: "A praia mais famosa do Brasil, com seu calçadão icônico e uma energia única.",
        preco: "R$120"
    },
    {
        nome: "Praia de Ipanema",
        coords: [-22.983956, -43.209587],
        imagem01: "images/passeios/cristoRedentor/CristoRedentor01.jpg",
        imagem02: "images/passeios/ipanema/Ipanema02.jpg",
        imagem03: "images/passeios/ipanema/Ipanema03.jpg",
        imagem04: "images/passeios/ipanema/Ipanema04.jpg",
        imagem05: "images/passeios/ipanema/Ipanema05.jpg",
        imagem06: "images/passeios/ipanema/Ipanema06.jpg",
        descricao: "Relaxe em uma das praias mais charmosas do mundo e aproveite o famoso pôr do sol.",
        preco: "R$130"
    },
    {
        nome: "Escadaria Selarón",
        coords: [-22.915235, -43.179221],
        imagem01: "images/passeios/cristoRedentor/CristoRedentor01.jpg",
        imagem02: "images/passeios/selaron/Selaron02.jpg",
        imagem03: "images/passeios/selaron/Selaron03.jpg",
        imagem04: "images/passeios/selaron/Selaron04.jpg",
        imagem05: "images/passeios/selaron/Selaron05.jpg",
        imagem06: "images/passeios/selaron/Selaron06.jpg",
        descricao: "Um dos pontos mais coloridos do Rio, perfeito para fotos e para conhecer arte urbana.",
        preco: "R$100"
    },
    {
        nome: "Lapa e Arcos da Lapa",
        coords: [-22.913708, -43.180409],
        imagem01: "images/passeios/cristoRedentor/CristoRedentor01.jpg",
        imagem02: "images/passeios/lapa/Lapa02.jpg",
        imagem03: "images/passeios/lapa/Lapa03.jpg",
        imagem04: "images/passeios/lapa/Lapa04.jpg",
        imagem05: "images/passeios/lapa/Lapa05.jpg",
        imagem06: "images/passeios/lapa/Lapa06.jpg",
        descricao: "Conheça a vida noturna carioca e os famosos Arcos da Lapa, símbolo histórico da cidade.",
        preco: "R$140"
    },
    {
        nome: "Parque Lage",
        coords: [-22.960762, -43.215937],
        imagem01: "images/passeios/cristoRedentor/CristoRedentor01.jpg",
        imagem02: "images/passeios/parquelage/Lage02.jpg",
        imagem03: "images/passeios/parquelage/Lage03.jpg",
        imagem04: "images/passeios/parquelage/Lage04.jpg",
        imagem05: "images/passeios/parquelage/Lage05.jpg",
        imagem06: "images/passeios/parquelage/Lage06.jpg",
        descricao: "Um refúgio verde com vista para o Cristo, perfeito para passeios tranquilos e fotos incríveis.",
        preco: "R$110"
    },
    {
        nome: "Mirante Dona Marta",
        coords: [-22.945814, -43.197566],
        imagem01: "images/passeios/cristoRedentor/CristoRedentor01.jpg",
        imagem02: "images/passeios/mirante/Mirante02.jpg",
        imagem03: "images/passeios/mirante/Mirante03.jpg",
        imagem04: "images/passeios/mirante/Mirante04.jpg",
        imagem05: "images/passeios/mirante/Mirante05.jpg",
        imagem06: "images/passeios/mirante/Mirante06.jpg",
        descricao: "Uma das melhores vistas panorâmicas do Rio, ideal para ver o nascer ou pôr do sol.",
        preco: "R$150"
    },
    {
        nome: "Outro",
        coords: [-22.945814, -43.197566],
        imagem01: "images/passeios/cristoRedentor/CristoRedentor01.jpg",
        imagem02: "images/passeios/mirante/Mirante02.jpg",
        imagem03: "images/passeios/mirante/Mirante03.jpg",
        imagem04: "images/passeios/mirante/Mirante04.jpg",
        imagem05: "images/passeios/mirante/Mirante05.jpg",
        imagem06: "images/passeios/mirante/Mirante06.jpg",
        descricao: "Uma das melhores vistas panorâmicas do Rio, ideal para ver o nascer ou pôr do sol.",
        preco: "R$150"
    }
];